### ISSUE TITLE
Passing byte arrays in dataset to report

### ISSUE THREAD

**Issue by KhalifaAjami** [gerardo-lijs/CrystalReportsRunner#12]
the report is using dataset made with net framework
in my net core app i pass in memory dataset with the same table name and columns
everything works but not the byte array

**Comment by gerardo-lijs** [comment]
Hello, sorry for the late reply. I was not exactly sure what you meant and was too busy to spend time trying to find out. Today I was able to reproduce this bug and will work on fixing this in the next days. Will keep you updated.

**Comment by KhalifaAjami** [comment]
@gerardo-lijs i fixed it
by passing the list of data as json string and then Deserialized it to list of objects , the down side of this is i needed to make the shell to have the classes that i used to serialize
![image](https://github.com/gerardo-lijs/CrystalReportsRunner/assets/120776909/7943e80a-6708-4b49-a796-6ee1e86cc3d3)

**Comment by KhalifaAjami** [comment]
i removed that dataset and used this because the dataset when serlizing the byte array it goes to base64 and when it is Deserialized it stays as base64 string

**Comment by KhalifaAjami** [comment]
the biggest down side right now that i have is that im using it with asp core api, when too many requests are called and are timed out or the api shuts down the proccess stays running the background

**Comment by gerardo-lijs** [comment]
Glad you found a qucik fix for now! I managed yesterday to create unit tests and isolate the byte[] serialization and next step I'm trying out the best solution to fix this, either going System.Text.Json route or https://github.com/MessagePack-CSharp/MessagePack-CSharp  writing custom converters.

I already have a working byte[] serialization over named pipes in another project I use, so the good news is this will be fixed completely in the core, and you can revert all the changes so that Shell class doesnt need to ref the classes.

Added a test button to test end to end sample over named pipes
![Step1](https://github.com/gerardo-lijs/CrystalReportsRunner/assets/14139570/2d0f6627-6919-4727-977a-018b0d4dee92)

Current code fails
![Step2](https://github.com/gerardo-lijs/CrystalReportsRunner/assets/14139570/7f6c6de1-7127-4a67-bc65-93dd00b67a0c)

Sample works using it directly in Unit Test
![Step3](https://github.com/gerardo-lijs/CrystalReportsRunner/assets/14139570/81a410b3-f5b9-4dda-9197-e2b199dc5bcc)

Working Unit Test to make sure serialization works perfectly for all types
![image](https://github.com/gerardo-lijs/CrystalReportsRunner/assets/14139570/1e928d05-13bc-4b53-a9e3-5aa6b3b9a083)

**Comment by gerardo-lijs** [comment]
> the biggest down side right now that i have is that im using it with asp core api, when too many requests are called and are timed out or the api shuts down the proccess stays running the background

Not sure if this is related or not to the changes you made or another issue. I have never used/tested the lib in asp core api, so we might need to create another sample app/use case for web api and check bugs/stability and how to deal with timeouts, etc. This is probably another issue we can work on after the serialization is fixed/done.

**Comment by gerardo-lijs** [comment]
Fixed! I will compile new version soon. You can check the changes, mainly DataSetJsonConverter method and the Unit Test DataSetJsonConverterTests in which I tried to cover most data type cases, unicode, nulls, etc.

![image](https://github.com/gerardo-lijs/CrystalReportsRunner/assets/14139570/150fd45c-b084-47d9-b812-b6faa19c1a79)
