### ISSUE TITLE
SP15 Support

### ISSUE THREAD

**Issue by anazhd** [gerardo-lijs/CrystalReportsRunner#33]
Hi, 

I'm working on a very old report and I would like to know if you are able to officially add/support SP15?

**Comment by anazhd** [comment]
@gerardo-lijs I did my custom runner, just I wish that we can have official support so I dont have to create an extra .NET Framework 4.8 inside my .NET 8.0 solution. I feel that it's a bit unclean.

How about I create a pull request with SP15 binaries, and a pair of new runner, and you add that as part of your publication? That will be awesome.

Just 1 thing that I'm not clear is that every pair of runner (x68 and x86) pointing to the same binary in CrystalReportsRunner\dependencies\13.0.x, so I did the same thing.

ps: I did check all the binaries PE inside the dependencies folder and well I found out that it's all actually x86

**Comment by gerardo-lijs** [comment]
Sure, if you can do a PR for that version, I can add it as another version/nuget in the same way we are supporting other versions. The CrystalReports dll files are the same for 32 and 64bits. We copy them to subfolder "dependencies\version" in this repo.

**Comment by enricoroselino** [comment]
@gerardo-lijs hello, is there any deep instructions ? 

some reference link is broken in : 
https://github.com/gerardo-lijs/CrystalReportsRunner/blob/main/docs/custom-runner.md 

or is there any repo that i can peek for guide ?

**Comment by gerardo-lijs** [comment]
Hi, the instructions/guide might need an update after 2+ years and might not be exactly a step by step guide. I will review them if possible over this weekend. Basically doing a copy/paste of an existing runner and changing the lib versions and dlls should be enough and very fast.

You need Runner for SP31 right? If you want, I can do it myself. Otherwise, if you prefer to learn, feel free to start working on it and send a PR. Please let me know.
