### ISSUE TITLE
Support for DSN

### ISSUE THREAD

**Issue by SohilAhmed** [gerardo-lijs/CrystalReportsRunner#4]
I really like your library and also works great, but this lacks support for DSN based reports. do you have any plan for that?

**Comment by gerardo-lijs** [comment]
Glad you liked it, we just released this we are using in case it helps other too! I don't have experience working with DSN based connections/reports, but if you can share what settings you use, for sure we can add a CreateDSNConnection in the file https://github.com/gerardo-lijs/CrystalReportsRunner/blob/main/src/LijsDev.CrystalReportsRunner.Core/CrystalReportsConnectionFactory.cs

to fit your needs and of other people using DSN.

**Comment by SohilAhmed** [comment]
_Your library is also missing TableLogOnInfo.ApplyLogOnInfo method to set connection to each table in case of DSN of SQL server connection for report_

**Comment by gerardo-lijs** [comment]
Not sure what issue you are experiencing, but we do set LogOnInfo to every table in every subreport. Take a look in the source file   https://github.com/gerardo-lijs/CrystalReportsRunner/blob/main/src/LijsDev.CrystalReportsRunner/shared/ReportUtils.cs   line 139.

Can you share a sample project with a DSN report that fails so we can try to help you? Otherwise, PR are also open if you can improve the library to be more compatible with the reports you are using.

The library was designed so you can create your own runner -> https://github.com/gerardo-lijs/CrystalReportsRunner/blob/main/docs/custom-runner.md   and just use the NamedPipes communication. This can probably fit any potential user need also.

**Comment by TechnVision** [comment]
done and closed
